package ccf.transport.json

import org.specs.Specification

object JsonDecoderSpec extends Specification {
  "Empty string" should {
    "parse to None" in {
      JsonDecoder.decodeResponse("") must equalTo(None)
    }
  }
  "Invalid JSON message" should {
    val invalidMessage = """{"a":1,"b":"c","d":3"""
    "cause MalformedDataException" in {
      JsonDecoder.decodeResponse(invalidMessage) must throwA[MalformedDataException]
    }
  }
  "A JSON response containing list as top-level element" should {
    "cause MalformedDataException" in {
      JsonDecoder.decodeResponse("[]") must throwA[MalformedDataException]
    }
  }
  "A JSON response containing improper header type" should {
    "cause MalformedDataException" in {
      JsonDecoder.decodeResponse("""{"headers":["foo","bar"]}""") must throwA[MalformedDataException]
    }
  }
  "A JSON response without header" should {
    "cause MalformedDataException" in {
      JsonDecoder.decodeResponse("""{"content":["foo","bar"]}""") must throwA[MalformedDataException]
    }
  }
  "A JSON response with headers but without content" should {
    val jsonResponse = """{"headers":{"aa":"bb","cc":"dd"}}"""
    "parse to equivalent Response" in {
      val expected = Response(Map[String, String]("aa" -> "bb", "cc" -> "dd"), None)
      val parsed = JsonDecoder.decodeResponse(jsonResponse).get
      parsed must equalTo(expected)
    }
  }
  "A JSON response with headers and content elements" should {
    val jsonResponse = """{"headers":{"aa":"bb","cc":"dd"},"content":{"b":2}}"""
    "parse to equivalent Response" in {
      val expected = Response(Map("aa" -> "bb", "cc" -> "dd"), Some(Map("b" -> 2)))
      val parsed = JsonDecoder.decodeResponse(jsonResponse).get
      parsed must equalTo(expected)
    }
  }
  "Response with content generated by JsonEncoder" should {
    val expected = Response(Map("key" -> "value"), Some(Map("a" -> 2)))
    val jsonResponse = JsonEncoder.encodeResponse(expected)
    "be properly parsed by JsonDecoder" in {
      val parsed = JsonDecoder.decodeResponse(jsonResponse).get
      parsed must equalTo(expected)
    }
  }
  "Response without content generated by JsonEncoder" should {
    val expected = Response(Map("key" -> "value"), None)
    val jsonResponse = JsonEncoder.encodeResponse(expected)
    "be properly parsed by JsonDecoder" in {
      val parsed = JsonDecoder.decodeResponse(jsonResponse).get
      parsed must equalTo(expected)
    }
  }
  "Request with content generated by JsonEncoder" should {
    val request = Request(Map("key" -> "value"), Some(Map("a" -> 1)))
    val jsonRequest = JsonEncoder.encodeRequest(request)
    "must be properly parsed to Response by JsonDecoder" in {
      val expected = Request(Map("key" -> "value"), Some(Map("a" -> 1)))
      val parsed = JsonDecoder.decodeRequest(jsonRequest).get
      parsed must equalTo(expected)
    }
  }
  "Request without content generated by JsonEncoder" should {
    val request = Request(Map("key" -> "value"), None)
    val jsonRequest = JsonEncoder.encodeRequest(request)
    "must be properly parsed to Response by JsonDecoder" in {
      val expected = Request(Map("key" -> "value"), None)
      val parsed = JsonDecoder.decodeRequest(jsonRequest).get
      parsed must equalTo(expected)
    }
  }
}
